version: "3.7"

services:
  db:
      image: postgres:11.5-alpine
      ports:
          - "5432:5432"
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=postgres
